server:
  port: 8803

#传给类的值
index: problems

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: zh-search



elasticsearch:
  host: 192.168.56.10
